(Encoding/Decoding) Problems 1~5
sclee-Github/LeetCode pull request #18
Opened 2022-09-28 01:50 UTC by sclee-Github

1. Decode XORed array
2. Decompress run-length encoded list
3. Shuffle string
4. Decode the message
5. Convert binary number in a linked list to integer
위의 5개 문제에 대한 PR 입니다.

2022-09-29 17:11 UTC, msk requested changes

2022-09-29 17:11 UTC, msk commented on src/decode_the_message.rs
> +        my_map.insert(c, eng_value as char);
`contains_key`와 `insert` 모두 해당 키값을 해시테이블에서 검색해야 하므로 같은 일을 두 번 하는 셈이 됩니다. [`entry`](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.entry)를 써서 한 번으로 줄이는 것이 효율적입니다.

2022-09-30 01:15 UTC, sclee-Github commented
4. Decode the message 문제에서 entry를 사용해서 해결하였습니다.

2022-09-30 01:23 UTC, msk approved these changes

2022-09-30 01:23 UTC, merged